#!/bin/sh
#
# My pairing and pair.io dotfiles bootstrap script.
#
# Usage:
# curl https://raw.github.com/jsmestad/.pair.io/master/bootstrap | sh

IAM=$(whoami)
DOT_ROOT=~/.jsmestad-pairio-dotfiles

rm -rf ~/.oh-my-zsh
rm -rf $DOT_ROOT

unlink ~/.vimrc.local
unlink ~/.gvimrc.local
unlink ~/.bash_profile
unlink ~/.bashrc
unlink ~/.gitconfig
unlink ~/.gemrc
unlink ~/.irbrc
unlink ~/.railsrc
unlink ~/.janus.rake
unlink ~/.tmux.conf
unlink ~/.zshrc

git clone https://github.com/robbyrussell/oh-my-zsh.git ~/.oh-my-zsh
git clone https://github.com/jsmestad/.pair.io.git ~/.jsmestad-pairio-dotfiles

ln -s -t ~/ $DOT_ROOT/.vimrc.local
ln -s -t ~/ $DOT_ROOT/.gvimrc.local
ln -s -t ~/ $DOT_ROOT/.bash_profile
ln -s -t ~/ $DOT_ROOT/.bashrc
ln -s -t ~/ $DOT_ROOT/.gitconfig
ln -s -t ~/ $DOT_ROOT/.gemrc
ln -s -t ~/ $DOT_ROOT/.irbrc
ln -s -t ~/ $DOT_ROOT/.railsrc
ln -s -t ~/ $DOT_ROOT/.janus.rake
ln -s -t ~/ $DOT_ROOT/.tmux.conf
ln -s -t ~/ $DOT_ROOT/.zshrc

git clone git://github.com/carlhuda/janus.git ~/.vim
cd ~/.vim && rake
