# skip_vim_plugin "command_t"
skip_vim_plugin "nerdtree"
skip_vim_plugin "jslint"

vim_plugin_task "scrooloose-nerdtree", "git://github.com/scrooloose/nerdtree.git"
vim_plugin_task "bufexplorer", "git://github.com/vim-scripts/bufexplorer.zip.git"
vim_plugin_task "handlebars", "git://github.com/nono/vim-handlebars.git"
vim_plugin_task "ruby", "git://github.com/vim-ruby/vim-ruby.git"
vim_plugin_task "rvm", "git://github.com/tpope/vim-rvm.git"
vim_plugin_task "bundler", "git://github.com/tpope/vim-bundler.git"
vim_plugin_task "abolish", "git://github.com/tpope/vim-abolish.git"
# vim_plugin_task "rake", "git://github.com/tpope/vim-rake.git"
# vim_plugin_task "rhubarb", "git://github.com/tpope/vim-rhubarb.git"
vim_plugin_task "vim-taglist-plus", "git://github.com/int3/vim-taglist-plus.git"
vim_plugin_task "jshint", "git://github.com/wookiehangover/jshint.vim.git"
